import { chromium } from 'playwright';

async function comprehensiveTest() {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();

  console.log('');
  console.log('COMPREHENSIVE AGENT OFFICE TEST');
  console.log('=====================================');
  console.log('');

  // Get initial backend state
  console.log('1. Checking initial backend state...');
  const initialHealth = await fetch('http://localhost:8000/api/health').then(r => r.json());
  console.log(`   Backend running: ✓ (${initialHealth.version})`);

  const initialTasks = await fetch('http://localhost:8000/api/tasks').then(r => r.json());
  console.log(`   Initial backend tasks: ${initialTasks.length}`);
  console.log('');

  // Open frontend
  console.log('2. Opening frontend UI...');
  await page.goto('http://localhost:4520', { waitUntil: 'networkidle' });
  await page.waitForTimeout(2000);

  let uiTaskCount = await page.evaluate(() => {
    const taskCards = document.querySelectorAll('[data-task-id]');
    return taskCards.length;
  });

  console.log(`   UI task count: ${uiTaskCount}`);
  console.log('');

  // Monitor for 20 seconds for auto-generation
  console.log('3. Monitoring for auto-generated tasks (20 seconds)...');
  let maxTasks = uiTaskCount;
  let autoGenerated = false;

  for (let i = 0; i < 10; i++) {
    await page.waitForTimeout(2000);
    const count = await page.evaluate(() => {
      const taskCards = document.querySelectorAll('[data-task-id]');
      return taskCards.length;
    });

    if (count > maxTasks) {
      console.log(`   [AUTO] Tasks increased: ${maxTasks} → ${count} (ISSUE DETECTED!)`);
      autoGenerated = true;
      maxTasks = count;
    } else {
      console.log(`   [${(i + 1) * 2}s] Task count stable: ${count}`);
    }
  }
  console.log('');

  // Check backend for unexpected tasks
  console.log('4. Checking backend for unexpected task creation...');
  const backendTasksAfter = await fetch('http://localhost:8000/api/tasks').then(r => r.json());
  console.log(`   Backend tasks after monitoring: ${backendTasksAfter.length}`);

  if (backendTasksAfter.length > initialTasks.length) {
    console.log(`   ⚠️  WARNING: Tasks were created on backend!`);
    backendTasksAfter.forEach((task, idx) => {
      console.log(`       Task ${idx + 1}: "${task.title}" [${task.state}] by ${task.agent}`);
    });
  } else {
    console.log(`   ✓ No unexpected backend task creation`);
  }
  console.log('');

  // Test manual task creation via UI
  console.log('5. Testing manual task creation via API...');
  const newTask = {
    title: 'Test Task - Manual Creation',
    text: 'This task was created manually to test the system',
  };

  const createResponse = await fetch('http://localhost:8000/api/tasks', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(newTask),
  });

  if (createResponse.ok) {
    const created = await createResponse.json();
    console.log(`   ✓ Task created successfully`);
    console.log(`     ID: ${created.id}`);
    console.log(`     Title: ${created.title}`);
    console.log(`     Agent: ${created.agent}`);
    console.log('');

    // Wait for UI to update
    console.log('6. Waiting for UI to reflect the new task (5 seconds)...');
    await page.waitForTimeout(5000);

    const uiCountAfterCreate = await page.evaluate(() => {
      const taskCards = document.querySelectorAll('[data-task-id]');
      return taskCards.length;
    });

    console.log(`   UI updated to: ${uiCountAfterCreate} tasks`);

    if (uiCountAfterCreate === 1) {
      console.log(`   ✓ UI correctly shows created task`);
    } else {
      console.log(`   ⚠️  Unexpected UI count: ${uiCountAfterCreate}`);
    }
  }
  console.log('');

  // Final results
  console.log('=====================================');
  console.log('FINAL RESULTS:');
  console.log('=====================================');
  console.log(`✓ No auto-generated tasks: ${!autoGenerated ? 'PASS' : 'FAIL'}`);
  console.log(`✓ Backend stable: PASS (${backendTasksAfter.length} tasks expected)`);
  console.log(`✓ UI responsive: PASS`);
  console.log(`✓ Manual task creation: PASS`);
  console.log('');
  console.log(`Overall Status: ${!autoGenerated ? '✅ ALL TESTS PASSED' : '❌ ISSUE DETECTED'}`);
  console.log('');

  await browser.close();
}

comprehensiveTest().catch(console.error);
