#!/usr/bin/env bash
# Detect business vertical, stack, and compliance posture from repo contents
# Outputs: BUSINESS_PROFILE.yaml at repo root
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE="$REPO_ROOT/BUSINESS_PROFILE.yaml"

log() { echo "[detect] $*"; }

vertical="saas"
compliance="none"
primary_stack="fullstack"
monetization="subscription"
scale="team"

# Detect vertical
if grep -rql "shopify\|woocommerce\|bigcommerce\|medusa" "$REPO_ROOT" 2>/dev/null; then
  vertical="ecommerce"
  monetization="transaction"
fi
if grep -rql "plaid\|fintech\|banking" "$REPO_ROOT" 2>/dev/null; then
  vertical="fintech"
fi
if grep -rql "FHIR\|HL7\|hipaa" "$REPO_ROOT" 2>/dev/null; then
  vertical="health"
fi
if grep -rql "FedRAMP\|fedramp" "$REPO_ROOT" 2>/dev/null; then
  vertical="government"
fi

# Detect compliance
if [[ -d "$REPO_ROOT/compliance" ]]; then
  compliance_flags=()
  grep -rql "soc2\|SOC2" "$REPO_ROOT/compliance" 2>/dev/null && compliance_flags+=("soc2")
  grep -rql "hipaa\|HIPAA" "$REPO_ROOT/compliance" 2>/dev/null && compliance_flags+=("hipaa")
  grep -rql "gdpr\|GDPR" "$REPO_ROOT/compliance" 2>/dev/null && compliance_flags+=("gdpr")
  grep -rql "pci\|PCI" "$REPO_ROOT/compliance" 2>/dev/null && compliance_flags+=("pci")
  if [[ ${#compliance_flags[@]} -gt 0 ]]; then
    compliance=$(IFS=+; echo "${compliance_flags[*]}")
  fi
fi

# Detect stack
if [[ -f "$REPO_ROOT/go.mod" ]]; then
  primary_stack="golang"
elif [[ -f "$REPO_ROOT/Cargo.toml" ]]; then
  primary_stack="rust"
elif [[ -f "$REPO_ROOT/backend/requirements.txt" || -f "$REPO_ROOT/pyproject.toml" ]]; then
  if [[ -d "$REPO_ROOT/frontend" ]]; then
    primary_stack="fullstack"
  else
    primary_stack="python"
  fi
elif [[ -f "$REPO_ROOT/package.json" ]]; then
  primary_stack="typescript"
fi

# Detect scale
agent_count=$(grep -c "^  - id:" "$REPO_ROOT/.claude/agents/_registry.yaml" 2>/dev/null || echo "0")
if (( agent_count > 100 )); then
  scale="enterprise"
elif (( agent_count > 20 )); then
  scale="team"
else
  scale="solo"
fi

log "Vertical: $vertical"
log "Compliance: $compliance"
log "Stack: $primary_stack"
log "Monetization: $monetization"
log "Scale: $scale"
log "Agents: $agent_count"

cat > "$PROFILE" << YAML
# Business Profile — Auto-detected
# Generated by scripts/detect-business.sh
# Re-run to update: ./scripts/detect-business.sh

vertical: $vertical
compliance: $compliance
primary_stack: $primary_stack
monetization: $monetization
scale: $scale
agent_count: $agent_count
detected_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || TZ=UTC date +"%Y-%m-%dT%H:%M:%SZ")
YAML

log "Profile written to $PROFILE"
