// Writes src/roster.gen.js from backend/app/seed/roster_seed.json so the UI's demo roster can never
// drift from the backend's seats. Only looks (hair, skin) are made up here, deterministically by id.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const HAIR = ['#111111', '#101820', '#20242e', '#5a2d0c', '#26140a', '#2d1a0a', '#1c1c2e', '#3d2814', '#0d0d0d', '#2a1a0e', '#8a4a1f', '#141414'];
const SKIN = ['#F0C9A0', '#B07850', '#F5D5B0', '#E0A878', '#E8B98E', '#9C6B43', '#C68B59', '#D89F70', '#8A5A32'];
const h = s => [...s].reduce((n, c) => (n * 31 + c.charCodeAt(0)) >>> 0, 7);

export function genRoster() {
  const seed = JSON.parse(readFileSync(path.join(ROOT, 'backend/app/seed/roster_seed.json'), 'utf8'));
  const rows = seed.agents.map(a => {
    const n = h(a.id);
    const o = { id: a.id, name: a.name, dept: a.dept, ...(a.lead ? { lead: true } : {}), grid: [0, 0], hair: HAIR[n % HAIR.length], skin: SKIN[(n >> 3) % SKIN.length] };
    return '  ' + JSON.stringify(o).replace(/"(\w+)":/g, '$1:').replace(/,/g, ', ').replace(/\[0, 0\]/, '[0, 0]') + ',';
  });
  const v1 = Object.fromEntries((seed.v1 || []).map(v => [v.id, { role: v.role, tagline: v.tagline }]));
  const text = `// GENERATED by scripts/gen_roster.mjs from backend/app/seed/roster_seed.json. Do not edit.\nexport const SEED_AGENTS = [\n${rows.join('\n')}\n];\nexport const SEED_V1 = ${JSON.stringify(v1, null, 1)};\n`;
  const file = path.join(ROOT, 'src', 'roster.gen.js');
  try { if (readFileSync(file, 'utf8') === text) return false; } catch {}
  writeFileSync(file, text);
  return true;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) console.log(genRoster() ? 'wrote src/roster.gen.js' : 'src/roster.gen.js up to date');
