// GENERATED by scripts/gen_roster.mjs from backend/app/seed/roster_seed.json. Do not edit.
export const SEED_AGENTS = [
  {id:"exec-ceo-strategist", name:"CEO STRATEGIST", dept:"exec", lead:true, grid:[0, 0], hair:"#2d1a0a", skin:"#8A5A32"},
  {id:"lexi", name:"VP SALES", dept:"revenue", lead:true, grid:[0, 0], hair:"#2a1a0e", skin:"#E8B98E"},
  {id:"ilm", name:"LEAD QUALIFIER", dept:"revenue", grid:[0, 0], hair:"#141414", skin:"#D89F70"},
  {id:"piper", name:"PROPOSAL WRITER", dept:"revenue", grid:[0, 0], hair:"#2d1a0a", skin:"#F0C9A0"},
  {id:"enzo", name:"PRICING ANALYST", dept:"revenue", grid:[0, 0], hair:"#101820", skin:"#B07850"},
  {id:"exec-vp-engineering", name:"VP ENGINEERING", dept:"engineering", lead:true, grid:[0, 0], hair:"#2a1a0e"},
  {id:"mlead", name:"FRONTEND LEAD", dept:"frontend", lead:true, grid:[0, 0], hair:"#1c1c2e", skin:"#9C6B43"},
  {id:"riley", name:"COMPONENT BUILDER", dept:"frontend", grid:[0, 0], hair:"#8a4a1f", skin:"#B07850"},
  {id:"gfx", name:"UI DESIGNER", dept:"frontend", grid:[0, 0], hair:"#20242e", skin:"#C68B59"},
  {id:"devops-cd", name:"DEVOPS LEAD", dept:"devops", lead:true, grid:[0, 0], hair:"#20242e"},
  {id:"sec-compliance", name:"SECURITY LEAD", dept:"secdata", lead:true, grid:[0, 0], hair:"#8a4a1f", skin:"#8A5A32"},
  {id:"alead", name:"FINANCE LEAD", dept:"fin", lead:true, grid:[0, 0], hair:"#1c1c2e", skin:"#E0A878"},
  {id:"invo", name:"PRICING MODELLER", dept:"fin", grid:[0, 0], hair:"#101820", skin:"#E8B98E"},
  {id:"apay", name:"USAGE & COST", dept:"fin", grid:[0, 0], hair:"#20242e", skin:"#B07850"},
  {id:"elead", name:"CONTENT EDITOR", dept:"content", lead:true, grid:[0, 0], hair:"#8a4a1f", skin:"#B07850"},
  {id:"newt", name:"DOCS WRITER", dept:"content", grid:[0, 0], hair:"#5a2d0c", skin:"#C68B59"},
  {id:"cmail", name:"STATUS WRITER", dept:"content", grid:[0, 0], hair:"#5a2d0c", skin:"#C68B59"},
];
export const SEED_V1 = {
 "exec-ceo-strategist": {
  "role": "CEO Strategist Agent",
  "tagline": "Runs intake and verify: is the idea worth building, and is the client real. Citadel: exec-ceo-strategist."
 },
 "lexi": {
  "role": "VP Sales Agent",
  "tagline": "Runs handoff: what the client receives, pricing and the deposit position. Citadel: exec-vp-sales."
 },
 "ilm": {
  "role": "Lead Qualifier Agent",
  "tagline": "Scores an incoming request against the ideal client and flags weak ones. Citadel: sales-lead-qualifier."
 },
 "piper": {
  "role": "Proposal Writer Agent",
  "tagline": "Drafts the proposal and scope summary the owner sends. Citadel: sales-proposal-gen."
 },
 "enzo": {
  "role": "Pricing Analyst Agent",
  "tagline": "Prices a build from scope and cost, and checks the margin. Citadel: sales-pricing."
 },
 "exec-vp-engineering": {
  "role": "VP Engineering Agent",
  "tagline": "Owns scope and build: acceptance criteria, task list, the patch review. Citadel: exec-vp-engineering."
 },
 "mlead": {
  "role": "Frontend Lead Agent",
  "tagline": "Owns the UI half of a build: pages, structure, the design system. Citadel: fe-page."
 },
 "riley": {
  "role": "Component Builder Agent",
  "tagline": "Builds and maintains UI components. Citadel: fe-component."
 },
 "gfx": {
  "role": "UI Designer Agent",
  "tagline": "Designs screens and visual assets. Citadel: design-ui."
 },
 "devops-cd": {
  "role": "DevOps Lead Agent",
  "tagline": "Owns the preview deploy and its checks. Citadel: devops-cd."
 },
 "sec-compliance": {
  "role": "Security Lead Agent",
  "tagline": "Owns the security stage and holds the security key on exposure. Citadel: sec-compliance."
 },
 "alead": {
  "role": "Finance Lead Agent",
  "tagline": "Owns unit economics and the per-job cost cap. Citadel: exec-cfo-finance."
 },
 "invo": {
  "role": "Pricing Modeller Agent",
  "tagline": "Models price against build and run cost. Citadel: fin-pricing."
 },
 "apay": {
  "role": "Usage and Cost Agent",
  "tagline": "Tracks token and infrastructure spend per job. Citadel: fin-usage."
 },
 "elead": {
  "role": "Content Editor Agent",
  "tagline": "Edits everything the client or owner reads. Citadel: content-editor."
 },
 "newt": {
  "role": "Docs Writer Agent",
  "tagline": "Writes the README and handoff docs. Citadel: content-docs."
 },
 "cmail": {
  "role": "Status Writer Agent",
  "tagline": "Writes status updates on a job. Citadel: content-status."
 }
};
