---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k3s_token: "CHANGE_ME"
  children:
    servers:
      hosts:
        server-1:
          ansible_host: 10.0.0.1
    agents:
      hosts:
        agent-1:
          ansible_host: 10.0.0.2
        agent-2:
          ansible_host: 10.0.0.3
